# .github/workflows/main.yml
name: Telegram Bot Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clear cache
        run: |
          rm -rf __pycache__
          find . -name "*.pyc" -delete

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Stop previous bot (if running)
        run: |
          pkill -9 -f "python bot.py" || true  # 强制杀死进程
          sleep 5  # 等待 5 秒

      - name: Check if bot is stopped
        run: |
          if pgrep -f "python bot.py"; then
            echo "Bot is still running!"
            exit 1  # 如果机器人仍在运行，则退出工作流程
          else
            echo "Bot is stopped."
          fi

      - name: Run Telegram Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          nohup python bot.py &
